# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ppezzull <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/02/20 16:34:09 by ppezzull          #+#    #+#              #
#    Updated: 2023/02/20 16:34:12 by ppezzull         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CLIENT_SRC = client.c
SERVER_SRC = server.c

CLIENT_NAME = client
SERVER_NAME = server

PRINTF = cd printf/ && make

CC = gcc
FLAGS = -Wall -Werror -Wextra

$(SERVER_NAME) : 

